//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCapas.Web.VentaProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaginationOfFacturaDto6X_P_SBETV", Namespace="http://schemas.datacontract.org/2004/07/ProyectoCapas.Host.Core")]
    [System.SerializableAttribute()]
    public partial class PaginationOfFacturaDto6X_P_SBETV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoCapas.Web.VentaProxy.FacturaDto[] itemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoCapas.Web.VentaProxy.FacturaDto[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page {
            get {
                return this.pageField;
            }
            set {
                if ((this.pageField.Equals(value) != true)) {
                    this.pageField = value;
                    this.RaisePropertyChanged("page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDto", Namespace="http://schemas.datacontract.org/2004/07/ProyectoCapas.Host.TransferObjects")]
    [System.SerializableAttribute()]
    public partial class FacturaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_clieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoCapas.Web.VentaProxy.DetalleDto[] detalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fech_ventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mon_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal num_factField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string num_fact_formatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_clie {
            get {
                return this.cod_clieField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_clieField, value) != true)) {
                    this.cod_clieField = value;
                    this.RaisePropertyChanged("cod_clie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoCapas.Web.VentaProxy.DetalleDto[] detalle {
            get {
                return this.detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleField, value) != true)) {
                    this.detalleField = value;
                    this.RaisePropertyChanged("detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fech_vent {
            get {
                return this.fech_ventField;
            }
            set {
                if ((this.fech_ventField.Equals(value) != true)) {
                    this.fech_ventField = value;
                    this.RaisePropertyChanged("fech_vent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mon_ape {
            get {
                return this.mon_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.mon_apeField, value) != true)) {
                    this.mon_apeField = value;
                    this.RaisePropertyChanged("mon_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal num_fact {
            get {
                return this.num_factField;
            }
            set {
                if ((this.num_factField.Equals(value) != true)) {
                    this.num_factField = value;
                    this.RaisePropertyChanged("num_fact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string num_fact_format {
            get {
                return this.num_fact_formatField;
            }
            set {
                if ((object.ReferenceEquals(this.num_fact_formatField, value) != true)) {
                    this.num_fact_formatField = value;
                    this.RaisePropertyChanged("num_fact_format");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleDto", Namespace="http://schemas.datacontract.org/2004/07/ProyectoCapas.Host.TransferObjects")]
    [System.SerializableAttribute()]
    public partial class DetalleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_artField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal num_factField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal prec_unicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cant {
            get {
                return this.cantField;
            }
            set {
                if ((this.cantField.Equals(value) != true)) {
                    this.cantField = value;
                    this.RaisePropertyChanged("cant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_art {
            get {
                return this.cod_artField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_artField, value) != true)) {
                    this.cod_artField = value;
                    this.RaisePropertyChanged("cod_art");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descrip {
            get {
                return this.descripField;
            }
            set {
                if ((object.ReferenceEquals(this.descripField, value) != true)) {
                    this.descripField = value;
                    this.RaisePropertyChanged("descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal num_fact {
            get {
                return this.num_factField;
            }
            set {
                if ((this.num_factField.Equals(value) != true)) {
                    this.num_factField = value;
                    this.RaisePropertyChanged("num_fact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal prec_unic {
            get {
                return this.prec_unicField;
            }
            set {
                if ((this.prec_unicField.Equals(value) != true)) {
                    this.prec_unicField = value;
                    this.RaisePropertyChanged("prec_unic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VentaProxy.IVentaService")]
    public interface IVentaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/GetListaFacturas", ReplyAction="http://tempuri.org/IVentaService/GetListaFacturasResponse")]
        ProyectoCapas.Web.VentaProxy.PaginationOfFacturaDto6X_P_SBETV GetListaFacturas(int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/GetListaFacturas", ReplyAction="http://tempuri.org/IVentaService/GetListaFacturasResponse")]
        System.Threading.Tasks.Task<ProyectoCapas.Web.VentaProxy.PaginationOfFacturaDto6X_P_SBETV> GetListaFacturasAsync(int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/SaveFactura", ReplyAction="http://tempuri.org/IVentaService/SaveFacturaResponse")]
        string SaveFactura(ProyectoCapas.Web.VentaProxy.FacturaDto facturaDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/SaveFactura", ReplyAction="http://tempuri.org/IVentaService/SaveFacturaResponse")]
        System.Threading.Tasks.Task<string> SaveFacturaAsync(ProyectoCapas.Web.VentaProxy.FacturaDto facturaDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/GetFactura", ReplyAction="http://tempuri.org/IVentaService/GetFacturaResponse")]
        ProyectoCapas.Web.VentaProxy.FacturaDto GetFactura(decimal num_fact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/GetFactura", ReplyAction="http://tempuri.org/IVentaService/GetFacturaResponse")]
        System.Threading.Tasks.Task<ProyectoCapas.Web.VentaProxy.FacturaDto> GetFacturaAsync(decimal num_fact);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentaServiceChannel : ProyectoCapas.Web.VentaProxy.IVentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentaServiceClient : System.ServiceModel.ClientBase<ProyectoCapas.Web.VentaProxy.IVentaService>, ProyectoCapas.Web.VentaProxy.IVentaService {
        
        public VentaServiceClient() {
        }
        
        public VentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoCapas.Web.VentaProxy.PaginationOfFacturaDto6X_P_SBETV GetListaFacturas(int page, int pageSize) {
            return base.Channel.GetListaFacturas(page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ProyectoCapas.Web.VentaProxy.PaginationOfFacturaDto6X_P_SBETV> GetListaFacturasAsync(int page, int pageSize) {
            return base.Channel.GetListaFacturasAsync(page, pageSize);
        }
        
        public string SaveFactura(ProyectoCapas.Web.VentaProxy.FacturaDto facturaDto) {
            return base.Channel.SaveFactura(facturaDto);
        }
        
        public System.Threading.Tasks.Task<string> SaveFacturaAsync(ProyectoCapas.Web.VentaProxy.FacturaDto facturaDto) {
            return base.Channel.SaveFacturaAsync(facturaDto);
        }
        
        public ProyectoCapas.Web.VentaProxy.FacturaDto GetFactura(decimal num_fact) {
            return base.Channel.GetFactura(num_fact);
        }
        
        public System.Threading.Tasks.Task<ProyectoCapas.Web.VentaProxy.FacturaDto> GetFacturaAsync(decimal num_fact) {
            return base.Channel.GetFacturaAsync(num_fact);
        }
    }
}
